name: E2E

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  e2e-default:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Run
        id: test-run
        uses: ./
        with:
          release_version_regexp: '^test-v?(?<major>[0-9]+)\.(?<minor>[0-9]+)\.(?<patch>[0-9]+).*$'

      - name: Assert placeholder
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.test-run.outputs.version }}
          expected: "v1.3.0"

  e2e:
    runs-on: ubuntu-latest
    if: always() && !cancelled()

    needs:
      - e2e-default

    steps:
      - name: Collect Results
        uses: ovsds/collect-needs-result-action@v1
        with:
          needs_json: ${{ toJson(needs) }}
          skip_allowed: false
