name: Push version tags

on:
  release:
    types: [published]

jobs:
  push-version-tags:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Push Version Tags
        uses: ovsds/push-version-tags-action@c16c3c8237d33f1db3b6c25465071843d920f9cd # v1.4.0
        with:
          version: ${{ github.event.release.tag_name }}
